version: '3.4'

services:
  groceries.service:
    image: ${DOCKER_REGISTRY-}groceriesservice
    volumes:
      - c:\temp\data:/data
    build:
      context: .
      dockerfile: Groceries.Service/Dockerfile

  groceries.web:
    image: ${DOCKER_REGISTRY-}groceriesweb
    ports:
      - "5000:80"
    environment:
      - GroceryServiceUri=http://groceries.service:80/api/Groceries
    build:
      context: .
      dockerfile: Groceries.Web/Dockerfile
