version: '3.4'

services:
  groceries.service:
    image: groceries.service
    build:
      context: Groceries.Service
      dockerfile: Dockerfile
    volumes:
      - c:\temp\data:/data

  groceries.web:
    image: groceries.web
    build:
      context: Groceries.Web
      dockerfile: Dockerfile
    ports:
      - "85:80"
    environment:
      - GroceryServiceUri=http://groceries.service/api/Groceries
    depends_on:
      - groceries.service
