version: '3.4'

services:
  groceries.service:
    image: ${DOCKER_REGISTRY-}groceriesservice
    build:
      context: .
      dockerfile: Groceries.Service/Dockerfile

  groceries.web:
    image: ${DOCKER_REGISTRY-}groceriesweb
    build:
      context: .
      dockerfile: Groceries.Web/Dockerfile

